Repository ICONICTHON/2024_ICONICTHON_TEAM_18_BE, pull requests merged in 2024-11, with the labels that each got.

#4 ⚙️ Setting - Domain 셋팅
  src/main/java/org/dongguk/onroad/OnRoadMainServerApplication.java
  src/main/java/org/dongguk/onroad/core/utility/S3Util.java
  src/main/java/org/dongguk/onroad/loadmap/application/controller/.keep
  src/main/java/org/dongguk/onroad/loadmap/application/dto/.keep
  src/main/java/org/dongguk/onroad/loadmap/application/service/.keep
  src/main/java/org/dongguk/onroad/loadmap/application/usecase/.keep
  src/main/java/org/dongguk/onroad/loadmap/domain/CheckPoint.java
  src/main/java/org/dongguk/onroad/loadmap/domain/Choice.java
  src/main/java/org/dongguk/onroad/loadmap/domain/Lecture.java
  src/main/java/org/dongguk/onroad/loadmap/domain/Quiz.java
  src/main/java/org/dongguk/onroad/loadmap/domain/Section.java
  src/main/java/org/dongguk/onroad/loadmap/domain/Subtopic.java
  src/main/java/org/dongguk/onroad/loadmap/domain/UserChoice.java
  src/main/java/org/dongguk/onroad/loadmap/domain/UserLecture.java
  src/main/java/org/dongguk/onroad/loadmap/domain/type/EQuizType.java
  src/main/java/org/dongguk/onroad/loadmap/domain/type/ESemester.java
  src/main/java/org/dongguk/onroad/loadmap/repository/CheckPointRepository.java
  src/main/java/org/dongguk/onroad/loadmap/repository/ChoiceRepository.java
  src/main/java/org/dongguk/onroad/loadmap/repository/LectureRepository.java
  src/main/java/org/dongguk/onroad/loadmap/repository/QuizRepository.java
  src/main/java/org/dongguk/onroad/loadmap/repository/SectionRepository.java
  src/main/java/org/dongguk/onroad/loadmap/repository/SubtopicRepository.java
  src/main/java/org/dongguk/onroad/loadmap/repository/UserChoiceRepository.java
  src/main/java/org/dongguk/onroad/loadmap/repository/UserLectureRepository.java
  src/main/java/org/dongguk/onroad/question/application/controller/.keep
  src/main/java/org/dongguk/onroad/question/application/dto/.keep
  src/main/java/org/dongguk/onroad/question/application/service/.keep
  src/main/java/org/dongguk/onroad/question/application/usecase/.keep
  src/main/java/org/dongguk/onroad/question/domain/Question.java
  src/main/java/org/dongguk/onroad/question/domain/Reply.java
  src/main/java/org/dongguk/onroad/question/repository/QuestionRepository.java
  src/main/java/org/dongguk/onroad/question/repository/ReplyRepository.java
  src/main/java/org/dongguk/onroad/security/domain/mysql/User.java
Labels: ⚙ Setting, 🐾 dongkyeomjang

#6 🔨 Refactor - Week Domain 추가 및 Lecture & Section & Quiz Domain 변경사항 반영
  src/main/java/org/dongguk/onroad/loadmap/domain/Lecture.java
  src/main/java/org/dongguk/onroad/loadmap/domain/Quiz.java
  src/main/java/org/dongguk/onroad/loadmap/domain/Section.java
  src/main/java/org/dongguk/onroad/loadmap/domain/Week.java
Labels: 🔨 Refactor, 🐾 dongkyeomjang

#8 🔨 Refactor - Lecture에 status 컬럼 추가
  src/main/java/org/dongguk/onroad/loadmap/domain/CheckPoint.java
  src/main/java/org/dongguk/onroad/loadmap/domain/Choice.java
  src/main/java/org/dongguk/onroad/loadmap/domain/Lecture.java
  src/main/java/org/dongguk/onroad/loadmap/domain/Quiz.java
  src/main/java/org/dongguk/onroad/loadmap/domain/Subtopic.java
  src/main/java/org/dongguk/onroad/loadmap/domain/type/EStatus.java
Labels: 🔨 Refactor, 🐾 dongkyeomjang

#11 ✨ Feature - 유저 정보 조회하기 API 구현
  http/auth/AuthControllerRequestHttp.http
  src/main/java/org/dongguk/onroad/core/constant/Constants.java
  src/main/java/org/dongguk/onroad/security/application/controller/AuthController.java
  src/main/java/org/dongguk/onroad/security/application/dto/response/ReadUserBriefResponseDto.java
  src/main/java/org/dongguk/onroad/security/application/service/ReadUserBriefService.java
  src/main/java/org/dongguk/onroad/security/application/usecase/ReadUserBriefUseCase.java
  src/main/java/org/dongguk/onroad/security/config/SecurityConfig.java
Labels: ✨ Feature, 🐾 dongkyeomjang

#17 🐞 BugFix - 내 과목 조회하기 쿼리 버그 해결
  http/roadmap/RoadmapControllerHttpRequest.http
  src/main/java/org/dongguk/onroad/roadmap/application/controller/RoadmapQueryV1Controller.java
  src/main/java/org/dongguk/onroad/roadmap/application/controller/query/RoadmapQueryV1Controller.java
  src/main/java/org/dongguk/onroad/roadmap/repository/UserLectureRepository.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#19 ✨ Feature - 3.2 로드맵 조회하기 API 구현
  http/roadmap/RoadmapControllerHttpRequest.http
  src/main/java/org/dongguk/onroad/question/domain/Question.java
  src/main/java/org/dongguk/onroad/roadmap/application/controller/query/RoadmapQueryV1Controller.java
  src/main/java/org/dongguk/onroad/roadmap/application/dto/response/.keep
  src/main/java/org/dongguk/onroad/roadmap/application/dto/response/ReadRoadmapResponseDto.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/ReadLectureBriefService.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/ReadLectureOverviewService.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/ReadRoadmapService.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/ReadLectureOverviewUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/ReadRoadmapUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/domain/CheckPoint.java
  src/main/java/org/dongguk/onroad/roadmap/domain/Choice.java
  src/main/java/org/dongguk/onroad/roadmap/domain/Lecture.java
  src/main/java/org/dongguk/onroad/roadmap/domain/Section.java
  src/main/java/org/dongguk/onroad/roadmap/domain/Subtopic.java
  src/main/java/org/dongguk/onroad/roadmap/domain/UserChoice.java
  src/main/java/org/dongguk/onroad/roadmap/domain/Week.java
  src/main/java/org/dongguk/onroad/roadmap/domain/service/LectureService.java
  src/main/java/org/dongguk/onroad/roadmap/repository/LectureRepository.java
  src/main/java/org/dongguk/onroad/roadmap/repository/SectionRepository.java
  src/main/java/org/dongguk/onroad/roadmap/repository/SubtopicRepository.java
  src/main/java/org/dongguk/onroad/roadmap/repository/UserLectureRepository.java
  src/main/java/org/dongguk/onroad/roadmap/repository/WeekRepository.java
  src/main/java/org/dongguk/onroad/security/domain/mysql/User.java
Labels: ✨ Feature, 🐾 dongkyeomjang

#21 ✨ Feature - 3.3 체크포인트 조회하기 API 구현
  http/roadmap/RoadmapControllerHttpRequest.http
  src/main/java/org/dongguk/onroad/roadmap/application/controller/query/RoadmapQueryV1Controller.java
  src/main/java/org/dongguk/onroad/roadmap/application/dto/response/ReadCheckPointSummaryResponseDto.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/ReadCheckPointSummaryService.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/ReadCheckPointSummaryUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/repository/CheckPointRepository.java
Labels: ✨ Feature, 🐾 dongkyeomjang

#23 ✨ Feature - 3.4 퀴즈 리스트 조회하기 API 구현
  http/roadmap/RoadmapControllerHttpRequest.http
  src/main/java/org/dongguk/onroad/roadmap/application/controller/query/RoadmapQueryV1Controller.java
  src/main/java/org/dongguk/onroad/roadmap/application/dto/response/ReadQuizSummaryResponseDto.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/ReadCheckPointSummaryService.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/ReadQuizSummaryService.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/ReadRoadmapService.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/ReadQuizSummaryUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/repository/CheckPointRepository.java
  src/main/java/org/dongguk/onroad/roadmap/repository/ChoiceRepository.java
  src/main/java/org/dongguk/onroad/roadmap/repository/QuizRepository.java
Labels: ✨ Feature, 🐾 dongkyeomjang

#25 🔨 Refactor - Lecture의 Status 세분화 / Filter 로직 삭제
  src/main/java/org/dongguk/onroad/roadmap/application/dto/response/ReadLectureBriefResponseDto.java
  src/main/java/org/dongguk/onroad/roadmap/application/dto/response/ReadLectureOverviewResponseDto.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/ReadLectureOverviewService.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/ReadLectureOverviewUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/domain/Lecture.java
  src/main/java/org/dongguk/onroad/roadmap/domain/service/LectureService.java
  src/main/java/org/dongguk/onroad/roadmap/domain/type/EStatus.java
Labels: 🔨 Refactor, 🐾 dongkyeomjang

#27 ✨ Feature - API_3.8 pdf 등록하기 구현
  http/roadmap/RoadmapControllerHttpRequest.http
  src/main/java/org/dongguk/onroad/OnRoadMainServerApplication.java
  src/main/java/org/dongguk/onroad/core/config/KafkaConfig.java
  src/main/java/org/dongguk/onroad/core/constant/Constants.java
  src/main/java/org/dongguk/onroad/core/listener/PdfListener.java
  src/main/java/org/dongguk/onroad/roadmap/application/controller/command/.keep
  src/main/java/org/dongguk/onroad/roadmap/application/controller/command/RoadmapCommandV1Controller.java
  src/main/java/org/dongguk/onroad/roadmap/application/controller/kafka/RoadmapKafkaConsumerV1Controller.java
  src/main/java/org/dongguk/onroad/roadmap/application/dto/kafka/CreateRoadmapDetailsKafkaResponseDto.java
  src/main/java/org/dongguk/onroad/roadmap/application/dto/request/.keep
  src/main/java/org/dongguk/onroad/roadmap/application/dto/request/CreateLectureRequestDto.java
  src/main/java/org/dongguk/onroad/roadmap/application/dto/response/ReadLectureOverviewResponseDto.java
  src/main/java/org/dongguk/onroad/roadmap/application/event/PdfEvent.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/CreateLectureService.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/CreateRoadmapDetailsService.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/CreateRoadmapService.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/ReadLectureBriefService.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/ReadLectureOverviewService.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/CreateLectureUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/CreateRoadmapDetailsUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/CreateRoadmapUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/domain/Week.java
  src/main/java/org/dongguk/onroad/roadmap/domain/service/SectionService.java
  src/main/java/org/dongguk/onroad/roadmap/domain/service/SubtopicService.java
  src/main/java/org/dongguk/onroad/roadmap/domain/service/UserLectureService.java
  src/main/java/org/dongguk/onroad/roadmap/domain/service/WeekService.java
  src/main/java/org/dongguk/onroad/roadmap/repository/WeekRepository.java
Labels: ✨ Feature, 🦖 jjuuuunnii

#33 🎇 Deploy: CI/CD workflow 생성
  .github/workflows/dev-cicd.yml
Labels: 🌏 Deploy, 🦖 jjuuuunnii

#35 📃 Docs - Dockerfile 추가
  Dockerfile
Labels: 📃 Docs, 🦖 jjuuuunnii

#39 🐛 BugFix: PDF 올리기 API 로직 수정
  http/roadmap/RoadmapControllerHttpRequest.http
  src/main/java/org/dongguk/onroad/core/config/KafkaConfig.java
  src/main/java/org/dongguk/onroad/core/utility/S3Util.java
  src/main/java/org/dongguk/onroad/roadmap/application/dto/kafka/CreateRoadmapDetailsKafkaResponseDto.java
  src/main/java/org/dongguk/onroad/roadmap/application/event/PdfEvent.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/CreateRoadmapDetailsService.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/CreateRoadmapService.java
  src/main/java/org/dongguk/onroad/roadmap/domain/CheckPoint.java
  src/main/java/org/dongguk/onroad/roadmap/domain/Section.java
  src/main/java/org/dongguk/onroad/roadmap/domain/Subtopic.java
  src/main/java/org/dongguk/onroad/roadmap/domain/Week.java
Labels: 🐞 BugFix, 🦖 jjuuuunnii

#41 🐛 BugFix: Work Flow 수정
  .github/workflows/dev-cicd.yml
Labels: 🐞 BugFix, 🦖 jjuuuunnii

#42 ✨ Feature - 4번대 API (질문 리스트 조회, 답변 리스트 조회, 질문하기, 답변하기) 구현
  http/question/QuestionControllerHttpRequest.http
  src/main/java/org/dongguk/onroad/core/utility/DateTimeUtil.java
  src/main/java/org/dongguk/onroad/question/application/controller/.keep
  src/main/java/org/dongguk/onroad/question/application/controller/command/QuestionCommandV1Controller.java
  src/main/java/org/dongguk/onroad/question/application/controller/query/QuestionQueryV1Controller.java
  src/main/java/org/dongguk/onroad/question/application/dto/.keep
  src/main/java/org/dongguk/onroad/question/application/dto/request/CreateQuestionRequestDto.java
  src/main/java/org/dongguk/onroad/question/application/dto/request/CreateReplyRequestDto.java
  src/main/java/org/dongguk/onroad/question/application/dto/response/ReadQuestionResponseDto.java
  src/main/java/org/dongguk/onroad/question/application/dto/response/ReadReplyResponseDto.java
  src/main/java/org/dongguk/onroad/question/application/service/.keep
  src/main/java/org/dongguk/onroad/question/application/service/CreateQuestionService.java
  src/main/java/org/dongguk/onroad/question/application/service/CreateReplyService.java
  src/main/java/org/dongguk/onroad/question/application/service/ReadQuestionService.java
  src/main/java/org/dongguk/onroad/question/application/service/ReadReplyService.java
  src/main/java/org/dongguk/onroad/question/application/usecase/.keep
  src/main/java/org/dongguk/onroad/question/application/usecase/CreateQuestionUseCase.java
  src/main/java/org/dongguk/onroad/question/application/usecase/CreateReplyUseCase.java
  src/main/java/org/dongguk/onroad/question/application/usecase/ReadQuestionUseCase.java
  src/main/java/org/dongguk/onroad/question/application/usecase/ReadReplyUseCase.java
  src/main/java/org/dongguk/onroad/question/domain/Question.java
  src/main/java/org/dongguk/onroad/question/domain/Reply.java
  src/main/java/org/dongguk/onroad/question/domain/service/QuestionService.java
  src/main/java/org/dongguk/onroad/question/domain/service/ReplyService.java
  src/main/java/org/dongguk/onroad/question/repository/QuestionRepository.java
  src/main/java/org/dongguk/onroad/question/repository/ReplyRepository.java
  src/main/java/org/dongguk/onroad/security/domain/service/UserService.java
Labels: ✨ Feature, 🐾 dongkyeomjang

#45 ✨ Feature - Quiz 생성하기 API 구현
  http/roadmap/RoadmapControllerHttpRequest.http
  src/main/java/org/dongguk/onroad/roadmap/application/controller/command/RoadmapCommandV1Controller.java
  src/main/java/org/dongguk/onroad/roadmap/application/dto/request/CreateQuizRequestDto.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/CreateQuizService.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/CreateQuizUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/domain/CheckPoint.java
  src/main/java/org/dongguk/onroad/roadmap/domain/Quiz.java
  src/main/java/org/dongguk/onroad/roadmap/domain/service/ChoiceService.java
  src/main/java/org/dongguk/onroad/roadmap/domain/service/QuizService.java
Labels: ✨ Feature, 🦖 jjuuuunnii

#46 📃 Docs - UseCase, Application Service, Controller 주석 추가
  src/main/java/org/dongguk/onroad/question/application/service/ReadQuestionService.java
  src/main/java/org/dongguk/onroad/question/application/service/ReadReplyService.java
  src/main/java/org/dongguk/onroad/question/application/usecase/CreateQuestionUseCase.java
  src/main/java/org/dongguk/onroad/question/application/usecase/CreateReplyUseCase.java
  src/main/java/org/dongguk/onroad/question/application/usecase/ReadQuestionUseCase.java
  src/main/java/org/dongguk/onroad/question/application/usecase/ReadReplyUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/application/controller/command/RoadmapCommandV1Controller.java
  src/main/java/org/dongguk/onroad/roadmap/application/controller/query/RoadmapQueryV1Controller.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/CreateLectureService.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/CreateRoadmapDetailsService.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/CreateRoadmapService.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/ReadLastUpdatedRoadMapService.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/ReadLectureOverviewService.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/ReadQuizSummaryService.java
  src/main/java/org/dongguk/onroad/roadmap/application/service/ReadRoadmapService.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/CreateLectureUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/CreateRoadmapDetailsUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/CreateRoadmapUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/CreateUserChoiceUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/ReadCheckPointSummaryUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/ReadLastUpdatedRoadmapUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/ReadLectureBriefUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/ReadLectureOverviewUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/ReadQuizSummaryUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/application/usecase/ReadRoadmapUseCase.java
  src/main/java/org/dongguk/onroad/roadmap/domain/service/LectureService.java
  src/main/java/org/dongguk/onroad/security/application/usecase/DeleteUserUseCase.java
  src/main/java/org/dongguk/onroad/security/application/usecase/LoginUseCase.java
  src/main/java/org/dongguk/onroad/security/application/usecase/LogoutUseCase.java
  src/main/java/org/dongguk/onroad/security/application/usecase/ReadUserBriefUseCase.java
  src/main/java/org/dongguk/onroad/security/application/usecase/ReissueJsonWebTokenUseCase.java
  src/main/java/org/dongguk/onroad/security/application/usecase/SignUpUseCase.java
Labels: 📃 Docs, 🐾 dongkyeomjang
